development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 10000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  host:    localhost
  adapter: postgresql
  encoding: UTF8
  database: dutchauction
  username: dutchauction
  password: X16524q1s8o05Si
  pool: 5
